version: "3.8"

services:
  app:
    build: .
    environment:
      - DSN=web:1234@tcp(mysql:3306)/snippetbox?parseTime=true
    depends_on:
      - mysql
    expose:
      - "4000"
    restart: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./security:/etc/nginx/security:ro
    depends_on:
      - app

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: web
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
